name: yes4track_mobile_api_client
version: 1.0.0
description: Caspian.Yes4Track.Service API
homepage: https://github.com/yes4track/
authors:
  - 'Yes4Track <admin@yes4track.com>'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: '>=4.0.0 <5.0.0'
  built_value: '>=8.0.4 <9.0.0'
  built_collection: '>=5.0.0 <6.0.0'

dev_dependencies:
  built_value_generator: '>=8.0.4 <9.0.0'
  build_runner: any
  test: '>=1.16.0 <1.17.0'
